apiVersion: v1
kind: Secret
metadata:
  name: tapas-db-secret
  namespace: tapas
  labels:
    app: tapas-db
type: Opaque
stringData:
  POSTGRES_DB: tapas
  POSTGRES_USER: tapas
  POSTGRES_PASSWORD: tapas_password
